vars:
  - params.yaml

stages:
  unpack_raw:
    cmd: python src/unpack_to_raw.py --bucket raw --dataset_dir data/raw
    deps:
    - .env
    - src/unpack_to_raw.py
    outs:
    - data/raw/
  process_staging:
    cmd: python src/process_to_staging.py --bucket_raw raw --input_file train.csv  
    deps:
    - .env
    - src/process_to_staging.py
  process_curated:
    cmd: python src/process_to_curated.py --mysql_name staging --mongo_db_name curated --mongo_collection wikitext --model_name distilbert-base-uncased
    deps:
    - .env
    - src/process_to_curated.py

